openapi: 3.0.3
info:
  title: STD24188
  description: This is a specification of STD24188
  version: "1.0.0"
servers:
  - url: http://localhost:8000
paths:
  /ping:
    get:
      summary: Ping the server
      description: Returns the text "pong"
      responses:
        "200":
          description: Successful ping
          content:
            text/plain:
              schema:
                type: string
                example: pong

  /cars:
    get:
      summary: list des voitures
      description: Returne liste voiture
      responses:
        "200":
          description: List of cars
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'

    post:
      summary: Create a new car
      description: Adds a new car to the in-memory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
      responses:
        "201":
          description: Car created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'

  /cars/{id}:
    get:
      summary: Get a car by its identifier
      description: Returns a car matching the given id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The identifier of the car
      responses:
        "200":
          description: Car found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
        "404":
          description: Car not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "La voiture avec l'id 1 n'existe ps."
 